stages:
  - build
  - deploy

variables:
  APPLICATION_NAME: self-postgrest
  CONTAINER_IMAGE_NAME: ${K8S_NAMESPACE}/${APPLICATION_NAME}
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY_URL}/${CONTAINER_IMAGE_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  K8S_IMAGE_PULL_SECRET_NAME: ecr-credentials

build-job:
  stage: build
  tags:
    - docker
  only:
    - main
  before_script:
    # Create repository if needed
    - >
      aws ecr create-repository --repository-name ${CONTAINER_IMAGE_NAME}
      || echo "Repository might have already existed"
  script:
    - docker build -t ${CONTAINER_IMAGE_TAGGED} .
    - docker push ${CONTAINER_IMAGE_TAGGED}

# Deploy to Kubernetes
deploy-job:
  stage: deploy
  tags:
    - docker
  only:
    - main
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -

