apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${K8S_SERVICE_ACCOUNT}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    users: "kevin_fabel@jtekt.co.jp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      serviceAccountName: ${K8S_SERVICE_ACCOUNT}
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          env:
            - name: PGRST_IMAGE
              value: postgrest/postgrest
            - name: NEXT_PUBLIC_PGRST_JWT_CLAIM_KEY
              value: http://10.115.1.100:30416/realms/jtekt/protocol/openid-connect/certs
            - name: NEXT_PUBLIC_PGRST_JWT_CLAIM_KEY
              value: email
            - name: K8S_NAMESPACE
              value: ${K8S_NAMESPACE}
            - name: NAME_PREFIX
              value: self
            - name: CLUSTER_ACCESS_URI
              value: http://172.16.98.151
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "600m"
      imagePullSecrets:
        - name: ${K8S_ECR_SECRET_NAME}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
  labels:
    app: ${APPLICATION_NAME}
spec:
  type: NodePort
  selector:
    app: ${APPLICATION_NAME}
  ports:
    - port: 3000
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: self-postgrest-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: self-postgrest-rolebinding
subjects:
  - kind: ServiceAccount
    name: ${K8S_SERVICE_ACCOUNT}
    namespace: ${K8S_NAMESPACE}
roleRef:
  kind: Role
  name: self-postgrest-role
  apiGroup: rbac.authorization.k8s.io
