// Generated by self-service-suite-icons-generator. Do not edit by hand.
import type { SVGProps } from "react";

export function AppIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width="1em"
      height="1em"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      {...props}
    >
      <path d="M7 7H5A2 2 0 0 0 3 9V17H5V13H7V17H9V9A2 2 0 0 0 7 7M7 11H5V9H7M14 7H10V17H12V13H14A2 2 0 0 0 16 11V9A2 2 0 0 0 14 7M14 11H12V9H14M20 9V15H21V17H17V15H18V9H17V7H21V9Z" fill="currentColor" />
      <g fill="#cf0000"><rect x="11" y="15.95" width="12.6" height="2.7" /><rect x="15.95" y="11.5" width="2.7" height="12.6" /></g>
    </svg>
  );
}
